const API_BASE_URL = "https://localhost:7059/api";

const API_ROUTES = {
  // ---- Auth ----
  register: `${API_BASE_URL}/auth/register`,
  login: `${API_BASE_URL}/auth/login`,
  verifyEmail: `${API_BASE_URL}/auth/verify-email`,
  resendVerification: `${API_BASE_URL}/auth/resend-verification`,
  forgotPassword: `${API_BASE_URL}/auth/forgot-password`,
  resetPassword: `${API_BASE_URL}/auth/reset-password`,
  setupAccount: `${API_BASE_URL}/auth/setup-account`,

  // ---- Professional ----
  professionalProfile: `${API_BASE_URL}/Professional/profile`,
  uploadProfilePicture: `${API_BASE_URL}/Professional/upload-profile-picture`,
  updateProfessionalProfile: `${API_BASE_URL}/Professional/update-professional-profile`,
  addExperience: `${API_BASE_URL}/Professional/add-experience`,
  addEducation: `${API_BASE_URL}/Professional/add-education`,
  addCertificate: `${API_BASE_URL}/Professional/add-certificate`,
  addProject: `${API_BASE_URL}/Professional/add-project`,
  addProfessionalSkill: `${API_BASE_URL}/Professional/add-professional-skills`,
    getSkills: `${API_BASE_URL}/Professional/skills`,

  // ---- Recruiter / Company (Module 3) ----
  createCompany: `${API_BASE_URL}/Recruiter`,
  joinCompany: `${API_BASE_URL}/Recruiter/join`,
  companyInvitationPreview: `${API_BASE_URL}/Recruiter/invitation`,
  inviteRecruiter: `${API_BASE_URL}/Recruiter/invite`,
  approveRecruiter: `${API_BASE_URL}/Recruiter/recruiters/approve`,
  removeRecruiter: `${API_BASE_URL}/Recruiter/recruiters`,
  updateCompanyProfile: `${API_BASE_URL}/Recruiter/profile`,
  uploadCompanyLogo: `${API_BASE_URL}/Recruiter/logo`,
  verifyCompany: `${API_BASE_URL}/Recruiter`,
  companyProfile: `${API_BASE_URL}/Recruiter`,
  companyTeam: `${API_BASE_URL}/Recruiter/team`,
  companyManagementOverview: `${API_BASE_URL}/Recruiter/management-overview`,
  recruiterProfile: `${API_BASE_URL}/Recruiter/profile`,


  // ---- Connections (Module 4 — Networking) ----
sendConnectionRequest: `${API_BASE_URL}/Connections/send-connection-request`,
acceptConnectionRequest: `${API_BASE_URL}/Connections/accept-connection-request`,
rejectConnectionRequest: `${API_BASE_URL}/Connections/reject-connection-request`,
cancelConnectionRequest: `${API_BASE_URL}/Connections/cancel-connection-request`,
removeConnection: `${API_BASE_URL}/Connections/remove-connection`,
followUser: `${API_BASE_URL}/Connections/follow-user`,
unfollowUser: `${API_BASE_URL}/Connections/unfollow-user`,
getMyConnections: `${API_BASE_URL}/Connections/my-connections`,
getReceivedRequests: `${API_BASE_URL}/Connections/received-requests`,
getSentRequests: `${API_BASE_URL}/Connections/sent-requests`,
getMyFollowers: `${API_BASE_URL}/Connections/my-followers`,
getMyFollowing: `${API_BASE_URL}/Connections/my-following`,
getConnectionSuggestions: `${API_BASE_URL}/Connections/suggestions`,


// ---- Posts (Module 5) ----
createPost: `${API_BASE_URL}/Posts/create-post`,
updatePost: `${API_BASE_URL}/Posts/update-post`,
deletePost: `${API_BASE_URL}/Posts/delete-post`,
sharePost: `${API_BASE_URL}/Posts/share-post`,
reactToPost: `${API_BASE_URL}/Posts/react`,
removeReaction: `${API_BASE_URL}/Posts/remove-reaction`,
addComment: `${API_BASE_URL}/Posts/add-comment`,
updateComment: `${API_BASE_URL}/Posts/update-comment`,
deleteComment: `${API_BASE_URL}/Posts/delete-comment`,
getFeed: `${API_BASE_URL}/Posts/feed`,
getPostById: `${API_BASE_URL}/Posts/post`,
getPostsByUser: `${API_BASE_URL}/Posts/user`,
getComments: `${API_BASE_URL}/Posts/comments`,
getUserPublicProfile: `${API_BASE_URL}/Users`,

// ---- Messaging (Module 6) ----
startConversation: `${API_BASE_URL}/Messages/start-conversation`,
createGroupConversation: `${API_BASE_URL}/Messages/create-group`,
addParticipant: `${API_BASE_URL}/Messages/add-participant`,
leaveConversation: `${API_BASE_URL}/Messages/leave-conversation`,
sendMessage: `${API_BASE_URL}/Messages/send-message`,
markConversationRead: `${API_BASE_URL}/Messages/mark-read`,
getMyConversations: `${API_BASE_URL}/Messages/conversations`,
getConversationMessages: `${API_BASE_URL}/Messages/messages`,
getConversationParticipants: `${API_BASE_URL}/Messages/participants`,
pinConversation: `${API_BASE_URL}/Messages/pin`,
unpinConversation: `${API_BASE_URL}/Messages/unpin`,
muteConversation: `${API_BASE_URL}/Messages/mute`,
unmuteConversation: `${API_BASE_URL}/Messages/unmute`,
hideConversation: `${API_BASE_URL}/Messages/hide`,
unhideConversation: `${API_BASE_URL}/Messages/unhide`,

  // ---- Job Management (Module 7) ----
  createJob: `${API_BASE_URL}/Job/create-job`,
  updateJob: `${API_BASE_URL}/Job/update-job`,
  publishJob: `${API_BASE_URL}/Job/publish-job`,
  closeJob: `${API_BASE_URL}/Job/close-job`,
  deleteJob: `${API_BASE_URL}/Job/delete-job`,
  applyJob: `${API_BASE_URL}/Job/apply-job`,
  updateApplicationStatus: `${API_BASE_URL}/Job/update-application-status`,
  saveJob: `${API_BASE_URL}/Job/save-job`,
  unsaveJob: `${API_BASE_URL}/Job/unsave-job`,
  createJobCategory: `${API_BASE_URL}/Job/create-job-category`,
  getJob: `${API_BASE_URL}/Job/job`,
  searchJobs: `${API_BASE_URL}/Job/search`,
  getJobsByRecruiter: `${API_BASE_URL}/Job/recruiter-jobs`,
  getSavedJobs: `${API_BASE_URL}/Job/saved-jobs`,
  getApplicationsByJob: `${API_BASE_URL}/Job/applications/job`,
  getApplicationsByProfessional: `${API_BASE_URL}/Job/applications/professional`,
  getJobCategories: `${API_BASE_URL}/Job/job-categories`,

  getApplicationsByRecruiter: `${API_BASE_URL}/Job/applications/recruiter`,
  scheduleInterview: `${API_BASE_URL}/Job/schedule-interview`,
  getApplicationStatusCounts: `${API_BASE_URL}/Job/applications/recruiter/status-counts`,
  uploadApplicationResume: `${API_BASE_URL}/Job/upload-application-resume`,
  addJobSkill: `${API_BASE_URL}/Job/add-job-skill`,
  removeJobSkill: `${API_BASE_URL}/Job/remove-job-skill`,
  getJobSkills: `${API_BASE_URL}/Job/job-skills`,

  getSkills: `${API_BASE_URL}/Professional/skills`,
  addJobSkill: `${API_BASE_URL}/Job/add-job-skill`,
  removeJobSkill: `${API_BASE_URL}/Job/remove-job-skill`,
  getJobSkills: `${API_BASE_URL}/Job/job-skills`,
  getJobSearchFacets: `${API_BASE_URL}/Job/search-facets`,
  getSuggestedJobTitles: `${API_BASE_URL}/Job/suggested-titles`,
  getApplicationStatusCountsByProfessional: `${API_BASE_URL}/Job/applications/professional/status-counts`,
  withdrawApplication: `${API_BASE_URL}/Job/withdraw-application`,

  getCompanyPublicProfile: `${API_BASE_URL}/Recruiter/public-profile`,
  getCompanyReviews: `${API_BASE_URL}/Recruiter/reviews`,
  getCompanyRatingSummary: `${API_BASE_URL}/Recruiter/rating-summary`,
  submitCompanyReview: `${API_BASE_URL}/Recruiter/submit-review`,
  markReviewHelpful: `${API_BASE_URL}/Recruiter/mark-review-helpful`,
  getPeopleYouMightKnow: `${API_BASE_URL}/Recruiter/people-you-might-know`,
  createJobAlert: `${API_BASE_URL}/Job/create-job-alert`,
  deleteJobAlert: `${API_BASE_URL}/Job/delete-job-alert`,
  toggleJobAlert: `${API_BASE_URL}/Job/toggle-job-alert`,
  getJobAlerts: `${API_BASE_URL}/Job/job-alerts`,
  getRecentActivity: `${API_BASE_URL}/Job/recent-activity`,
  getRecommendedJobs: `${API_BASE_URL}/Job/recommended`,

  // ---- Notifications (Module 8) ----
getNotifications: `${API_BASE_URL}/Notifications`,
getUnreadNotificationCount: `${API_BASE_URL}/Notifications/unread-count`,
markNotificationRead: `${API_BASE_URL}/Notifications/mark-read`,
markAllNotificationsRead: `${API_BASE_URL}/Notifications/mark-all-read`,

  // ---- Analytics (Module 10) ----
  getProfessionalAnalyticsDashboard: `${API_BASE_URL}/Analytics/professional/dashboard`,
  getRecruiterAnalyticsDashboard: `${API_BASE_URL}/Analytics/recruiter/dashboard`,
  getJobAnalytics: `${API_BASE_URL}/Analytics/recruiter/jobs`,
  getApplicationFunnelAnalytics: `${API_BASE_URL}/Analytics/recruiter/funnel`,
  getJobViewsAnalytics: `${API_BASE_URL}/Analytics/recruiter/job-views`,
  getProfessionalPostAnalytics: `${API_BASE_URL}/Analytics/professional/posts`,
  getProfessionalViewsAnalytics: `${API_BASE_URL}/Analytics/professional/views`,
  getPostImpressionsAnalytics: `${API_BASE_URL}/Analytics/professional/post-impressions`,
  getProfileDemographicsAnalytics: `${API_BASE_URL}/Analytics/professional/demographics`,

  // ---- Events (Module 9) ----
  createEvent: `${API_BASE_URL}/Event/create-event`,
  updateEvent: `${API_BASE_URL}/Event/update-event`,
  publishEvent: `${API_BASE_URL}/Event/publish-event`,
  cancelEvent: `${API_BASE_URL}/Event/cancel-event`,
  deleteEvent: `${API_BASE_URL}/Event/delete-event`,
  uploadEventCoverImage: `${API_BASE_URL}/Event/upload-cover-image`,
  addEventSpeaker: `${API_BASE_URL}/Event/add-speaker`,
  updateEventSpeaker: `${API_BASE_URL}/Event/update-speaker`,
  removeEventSpeaker: `${API_BASE_URL}/Event/remove-speaker`,
  addEventAgendaItem: `${API_BASE_URL}/Event/add-agenda-item`,
  updateEventAgendaItem: `${API_BASE_URL}/Event/update-agenda-item`,
  removeEventAgendaItem: `${API_BASE_URL}/Event/remove-agenda-item`,
  updateEventRegistrationStatus: `${API_BASE_URL}/Event/update-registration-status`,
  getManagedEvents: `${API_BASE_URL}/Event/managed-events`,
  getEventForManage: `${API_BASE_URL}/Event/manage`,
  getEventRegistrations: `${API_BASE_URL}/Event/registrations`,
  uploadEventRegistrationResume: `${API_BASE_URL}/Event/upload-registration-resume`,
  registerForEvent: `${API_BASE_URL}/Event/register`,
  cancelEventRegistration: `${API_BASE_URL}/Event/cancel-registration`,
  saveEvent: `${API_BASE_URL}/Event/save`,
  unsaveEvent: `${API_BASE_URL}/Event/unsave`,
  discoverEvents: `${API_BASE_URL}/Event/discover`,
  getFeaturedEvents: `${API_BASE_URL}/Event/featured`,
  getEventDetails: `${API_BASE_URL}/Event/`,
  getMyEvents: `${API_BASE_URL}/Event/my-events`,
  getEventAttendees: `${API_BASE_URL}/Event/attendees`,
};

